name: Otomatik Konfliktsiz Merge ve Push

on:
  push:
    branches:
      - ismail # "ismail" branşına push olduğunda çalışır

jobs:
  merge_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Code'u Al
        uses: actions/checkout@v3

      - name: Git'i Kur
        run: |
          git config --global user.name "Otomatik Merge Bot"
          git config --global user.email "bot@example.com"

      - name: Main'i Fetch Et
        run: git fetch origin main

      - name: Main ile Merge ve Push
        run: |
          git checkout main
          git pull origin main
          git merge origin/ismail
          git commit -m "Otomatik merge: ismail'den main'e"
          git push origin main
